spring:
  profiles:
    default: create

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secretKey: ${JWT_TOKEN}

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh