spring:
  redis:
    pool:
      max-idle: 8
      max-active: 8
    port: 6379
    host: 127.0.0.1

  profiles:
    default: prod

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secretKey: 544ec6cb127724963dd908fd356bb5fd3fc9f1c19980015ffdbb2aea4833d79afbe405495db7608be94ba5b8d3e6fcaa71eefbb0a84f15943617e969e3afe3d

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh
