spring:

  profiles:
    include: oauth, jwt

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

domain:
  name: http://www.localhost:8080

