spring:
  redis:
    pool:
      max-idle: 8
      max-active: 8
    port: 6379
    host: 127.0.0.1

  profiles:
    default: prod

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secretKey: ${JWT_TOKEN}

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh

server:
  port: 3000
